# Generated by Django 5.1.5 on 2025-03-10 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_product_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
