# Generated by Django 5.1.3 on 2024-11-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_test2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
