# Generated by Django 5.1.5 on 2025-03-10 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_product_popularity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
