# Generated by Django 4.2.16 on 2024-11-11 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
