# Generated by Django 5.1.3 on 2025-03-11 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0003_product_voters"),
        ("MyApp", "0003_remove_product_location"),
    ]

    operations = []
