# Generated by Django 5.1.6 on 2025-03-26 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_merge_20250310_1854'),
        ('MyApp', '0005_productimage'),
    ]

    operations = [
    ]
