# Generated by Django 5.1.5 on 2025-03-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_merge_20250310_2353'),
        ('MyApp', '0005_productimage'),
    ]

    operations = [
    ]
