# Generated by Django 5.1.6 on 2025-02-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_delete_test2'),
        ('MyApp', '0005_product_image'),
    ]

    operations = [
    ]
