# Generated by Django 5.1.6 on 2025-03-31 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_merge_0004_merge_20250310_1854_0005_productimage'),
        ('MyApp', '0007_product_views'),
    ]

    operations = [
    ]
