# Generated by Django 5.1.3 on 2025-04-14 04:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0004_merge_20250311_0029"),
        ("MyApp", "0008_merge_20250331_1631"),
    ]

    operations = []
