# Generated by Django 5.1.3 on 2025-04-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyApp", "0010_alter_product_image_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clothing", "Clothing"),
                    ("accessories", "Accessories"),
                    ("tickets", "Tickets"),
                    ("studyMaterials", "Study Materials"),
                    ("miscellaneous", "Miscellaneous"),
                    ("sublease", "Sublease"),
                ],
                max_length=50,
            ),
        ),
    ]
