# Generated by Django 5.1.6 on 2025-04-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_alter_product_category_alter_product_image_and_more'),
        ('MyApp', '0010_profile'),
    ]

    operations = [
    ]
